[package]
name = "manga-ocr"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
clap = { version = "4.5.8", features = ["derive"] }
eyre = "0.6.12"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.118"
ureq = { version = "2.9.7", features = ["json"] }
